# Generated by Django 2.2.5 on 2019-09-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dbLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddress', models.CharField(max_length=15)),
                ('dateLog', models.DateTimeField()),
                ('httpMethod', models.CharField(max_length=5)),
                ('uriLog', models.TextField()),
                ('numError', models.IntegerField()),
                ('sizeAnswer', models.IntegerField()),
            ],
        ),
    ]
