# Generated by Django 2.2.1 on 2019-09-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parserLink', '0002_auto_20190912_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15, unique=True)),
                ('ip_count', models.IntegerField()),
            ],
        ),
    ]
