# Generated by Django 2.2.1 on 2019-09-15 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parserLink', '0004_auto_20190915_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IP_address',
        ),
    ]
