# Generated by Django 2.2.1 on 2019-09-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=15)),
                ('date_log', models.DateTimeField()),
                ('http_method', models.CharField(db_index=True, max_length=10)),
                ('uri_log', models.TextField()),
                ('num_error', models.IntegerField()),
                ('size_answer', models.IntegerField()),
            ],
        ),
    ]
