# Generated by Django 2.2.1 on 2019-09-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('date_log', models.DateTimeField()),
                ('http_method', models.TextField(db_index=True, null=True)),
                ('uri_log', models.TextField(null=True)),
                ('num_error', models.IntegerField(null=True)),
                ('size_answer', models.IntegerField(null=True)),
            ],
        ),
    ]
