# Generated by Django 2.2.1 on 2019-09-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_command', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='http_method',
            field=models.CharField(db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='num_error',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='size_answer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='uri_log',
            field=models.TextField(null=True),
        ),
    ]
